import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import "./globals.css";
import "./style.css";

export const metadata: Metadata = {
  title: "Nwike Odigwe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-background text-gray-200 font-sans`}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
